version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_HOST: db
      CONNECTION_STRING: root:root@tcp(db:3306)/shortener?charset=utf8mb4&parseTime=True&loc=Local

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortener
      MYSQL_USER: MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
